"""
Eagle Vision — Realistic Demo Seed Data
Creates 20 employees, skills, departments, projects, and learning resources.
Designed to demonstrate meaningful HR matching differences.
"""

import json
import uuid
from datetime import date, datetime, timezone
from typing import Any, Dict, List


def get_seed_data() -> Dict[str, Any]:
    """
    Returns all seed data as Python dicts for insertion.
    Employees are designed so Arun > Priya > Vignesh > Karthik for AI backend roles.
    """

    # ── Departments ─────────────────────────────────────────────────────────
    departments = [
        {"id": "dept-eng", "name": "Engineering", "description": "Software engineering teams", "head_count": 45},
        {"id": "dept-data", "name": "Data & AI", "description": "Data science and AI teams", "head_count": 18},
        {"id": "dept-prod", "name": "Product", "description": "Product management and design", "head_count": 12},
        {"id": "dept-ops", "name": "Operations", "description": "DevOps and infrastructure", "head_count": 8},
        {"id": "dept-hr", "name": "Human Resources", "description": "HR and talent management", "head_count": 6},
    ]

    # ── Skills ───────────────────────────────────────────────────────────────
    skill_categories = [
        {"id": "cat-backend", "name": "Backend Development"},
        {"id": "cat-frontend", "name": "Frontend Development"},
        {"id": "cat-ai", "name": "AI & Machine Learning"},
        {"id": "cat-devops", "name": "DevOps & Cloud"},
        {"id": "cat-data", "name": "Data Engineering"},
        {"id": "cat-soft", "name": "Soft Skills"},
    ]

    skills = [
        {"id": "sk-python", "name": "Python", "category_id": "cat-backend", "skill_type": "technical"},
        {"id": "sk-fastapi", "name": "FastAPI", "category_id": "cat-backend", "skill_type": "technical"},
        {"id": "sk-django", "name": "Django", "category_id": "cat-backend", "skill_type": "technical"},
        {"id": "sk-postgresql", "name": "PostgreSQL", "category_id": "cat-backend", "skill_type": "technical"},
        {"id": "sk-restapi", "name": "REST API", "category_id": "cat-backend", "skill_type": "technical"},
        {"id": "sk-docker", "name": "Docker", "category_id": "cat-devops", "skill_type": "technical"},
        {"id": "sk-kubernetes", "name": "Kubernetes", "category_id": "cat-devops", "skill_type": "technical"},
        {"id": "sk-ml", "name": "Machine Learning", "category_id": "cat-ai", "skill_type": "technical"},
        {"id": "sk-pytorch", "name": "PyTorch", "category_id": "cat-ai", "skill_type": "technical"},
        {"id": "sk-react", "name": "React", "category_id": "cat-frontend", "skill_type": "technical"},
        {"id": "sk-typescript", "name": "TypeScript", "category_id": "cat-frontend", "skill_type": "technical"},
        {"id": "sk-redis", "name": "Redis", "category_id": "cat-backend", "skill_type": "technical"},
        {"id": "sk-aws", "name": "AWS", "category_id": "cat-devops", "skill_type": "technical"},
        {"id": "sk-nlp", "name": "NLP", "category_id": "cat-ai", "skill_type": "technical"},
        {"id": "sk-sql", "name": "SQL", "category_id": "cat-data", "skill_type": "technical"},
        {"id": "sk-git", "name": "Git", "category_id": "cat-backend", "skill_type": "technical"},
        {"id": "sk-celery", "name": "Celery", "category_id": "cat-backend", "skill_type": "technical"},
        {"id": "sk-graphql", "name": "GraphQL", "category_id": "cat-backend", "skill_type": "technical"},
        {"id": "sk-vue", "name": "Vue.js", "category_id": "cat-frontend", "skill_type": "technical"},
        {"id": "sk-agile", "name": "Agile", "category_id": "cat-soft", "skill_type": "soft"},
    ]

    # ── HR Users ─────────────────────────────────────────────────────────────
    from app.core.security import get_password_hash
    HR_HASH = get_password_hash("password123")

    users = [
        {
            "id": "user-hr-admin",
            "email": "hr@eaglevision.ai",
            "hashed_password": HR_HASH,
            "full_name": "Sarah HR Admin",
            "role": "hr_admin",
            "is_active": True,
        },
        {
            "id": "user-hr-2",
            "email": "talent@eaglevision.ai",
            "hashed_password": HR_HASH,
            "full_name": "Meera Talent",
            "role": "hr",
            "is_active": True,
        },
    ]

    # ── Employees (20 real profiles) ─────────────────────────────────────────
    employees = [
        # --- Top match: Arun — Python, FastAPI, PostgreSQL, REST API, Redis ---
        {
            "id": "emp-arun",
            "first_name": "Arun",
            "last_name": "Kumar",
            "job_title": "Senior Backend Engineer",
            "department": "Engineering",
            "location": "Chennai, India",
            "bio": "Experienced backend engineer specializing in Python microservices and AI integrations.",
            "years_of_experience": 4.5,
            "open_to_remote": True,
            "open_to_gigs": True,
            "skills": [
                {"skill_id": "sk-python", "proficiency_level": 5, "years_of_experience": 4.0},
                {"skill_id": "sk-fastapi", "proficiency_level": 4, "years_of_experience": 2.5},
                {"skill_id": "sk-postgresql", "proficiency_level": 4, "years_of_experience": 3.0},
                {"skill_id": "sk-restapi", "proficiency_level": 5, "years_of_experience": 4.0},
                {"skill_id": "sk-redis", "proficiency_level": 3, "years_of_experience": 1.5},
                {"skill_id": "sk-git", "proficiency_level": 5, "years_of_experience": 4.0},
                {"skill_id": "sk-ml", "proficiency_level": 2, "years_of_experience": 0.5},
                {"skill_id": "sk-sql", "proficiency_level": 4, "years_of_experience": 3.5},
            ],
        },
        # --- 2nd match: Priya — Python, FastAPI, PostgreSQL, REST API. No Docker, less ML ---
        {
            "id": "emp-priya",
            "first_name": "Priya",
            "last_name": "Sharma",
            "job_title": "Backend Developer",
            "department": "Engineering",
            "location": "Bangalore, India",
            "bio": "Full-stack backend developer with strong Python and API development skills.",
            "years_of_experience": 3.0,
            "open_to_remote": True,
            "open_to_gigs": True,
            "skills": [
                {"skill_id": "sk-python", "proficiency_level": 4, "years_of_experience": 3.0},
                {"skill_id": "sk-fastapi", "proficiency_level": 3, "years_of_experience": 1.5},
                {"skill_id": "sk-postgresql", "proficiency_level": 3, "years_of_experience": 2.0},
                {"skill_id": "sk-restapi", "proficiency_level": 4, "years_of_experience": 3.0},
                {"skill_id": "sk-django", "proficiency_level": 4, "years_of_experience": 2.5},
                {"skill_id": "sk-git", "proficiency_level": 4, "years_of_experience": 3.0},
                {"skill_id": "sk-sql", "proficiency_level": 3, "years_of_experience": 2.0},
            ],
        },
        # --- 3rd match: Vignesh — Python, PostgreSQL, REST API. No FastAPI, no Docker ---
        {
            "id": "emp-vignesh",
            "first_name": "Vignesh",
            "last_name": "Ramachandran",
            "job_title": "Backend Engineer",
            "department": "Engineering",
            "location": "Hyderabad, India",
            "bio": "Backend developer with Django and Flask experience. Currently upskilling in FastAPI.",
            "years_of_experience": 2.5,
            "open_to_remote": True,
            "open_to_gigs": True,
            "skills": [
                {"skill_id": "sk-python", "proficiency_level": 4, "years_of_experience": 2.5},
                {"skill_id": "sk-django", "proficiency_level": 4, "years_of_experience": 2.0},
                {"skill_id": "sk-postgresql", "proficiency_level": 3, "years_of_experience": 1.5},
                {"skill_id": "sk-restapi", "proficiency_level": 3, "years_of_experience": 2.0},
                {"skill_id": "sk-sql", "proficiency_level": 3, "years_of_experience": 2.0},
                {"skill_id": "sk-git", "proficiency_level": 3, "years_of_experience": 2.5},
                {"skill_id": "sk-redis", "proficiency_level": 2, "years_of_experience": 0.5},
            ],
        },
        # --- 4th match: Karthik — Python only, 1.5 yrs ---
        {
            "id": "emp-karthik",
            "first_name": "Karthik",
            "last_name": "Subramanian",
            "job_title": "Junior Python Developer",
            "department": "Engineering",
            "location": "Chennai, India",
            "bio": "Junior developer with Python experience. Good problem-solving skills.",
            "years_of_experience": 1.5,
            "open_to_remote": True,
            "open_to_gigs": True,
            "skills": [
                {"skill_id": "sk-python", "proficiency_level": 3, "years_of_experience": 1.5},
                {"skill_id": "sk-sql", "proficiency_level": 2, "years_of_experience": 1.0},
                {"skill_id": "sk-git", "proficiency_level": 3, "years_of_experience": 1.5},
                {"skill_id": "sk-restapi", "proficiency_level": 2, "years_of_experience": 0.5},
            ],
        },
        # --- More employees ---
        {
            "id": "emp-divya",
            "first_name": "Divya",
            "last_name": "Nair",
            "job_title": "ML Engineer",
            "department": "Data & AI",
            "location": "Pune, India",
            "bio": "ML engineer focused on NLP and deep learning model deployment.",
            "years_of_experience": 3.5,
            "open_to_remote": True,
            "open_to_gigs": True,
            "skills": [
                {"skill_id": "sk-python", "proficiency_level": 5, "years_of_experience": 3.5},
                {"skill_id": "sk-ml", "proficiency_level": 5, "years_of_experience": 3.0},
                {"skill_id": "sk-pytorch", "proficiency_level": 4, "years_of_experience": 2.0},
                {"skill_id": "sk-nlp", "proficiency_level": 4, "years_of_experience": 2.0},
                {"skill_id": "sk-docker", "proficiency_level": 3, "years_of_experience": 1.5},
                {"skill_id": "sk-sql", "proficiency_level": 3, "years_of_experience": 2.0},
                {"skill_id": "sk-fastapi", "proficiency_level": 3, "years_of_experience": 1.0},
            ],
        },
        {
            "id": "emp-ravi",
            "first_name": "Ravi",
            "last_name": "Krishnan",
            "job_title": "DevOps Engineer",
            "department": "Operations",
            "location": "Mumbai, India",
            "bio": "DevOps specialist with strong containerization and CI/CD expertise.",
            "years_of_experience": 5.0,
            "open_to_remote": True,
            "open_to_gigs": True,
            "skills": [
                {"skill_id": "sk-docker", "proficiency_level": 5, "years_of_experience": 4.0},
                {"skill_id": "sk-kubernetes", "proficiency_level": 5, "years_of_experience": 3.0},
                {"skill_id": "sk-aws", "proficiency_level": 4, "years_of_experience": 3.5},
                {"skill_id": "sk-python", "proficiency_level": 3, "years_of_experience": 2.0},
                {"skill_id": "sk-git", "proficiency_level": 5, "years_of_experience": 5.0},
            ],
        },
        {
            "id": "emp-ananya",
            "first_name": "Ananya",
            "last_name": "Iyer",
            "job_title": "Full Stack Developer",
            "department": "Engineering",
            "location": "Bangalore, India",
            "bio": "Full stack developer skilled in React and Python backend services.",
            "years_of_experience": 3.0,
            "open_to_remote": True,
            "open_to_gigs": True,
            "skills": [
                {"skill_id": "sk-react", "proficiency_level": 4, "years_of_experience": 2.5},
                {"skill_id": "sk-typescript", "proficiency_level": 4, "years_of_experience": 2.0},
                {"skill_id": "sk-python", "proficiency_level": 3, "years_of_experience": 2.0},
                {"skill_id": "sk-restapi", "proficiency_level": 3, "years_of_experience": 2.0},
                {"skill_id": "sk-git", "proficiency_level": 4, "years_of_experience": 3.0},
            ],
        },
        {
            "id": "emp-rohan",
            "first_name": "Rohan",
            "last_name": "Mehta",
            "job_title": "Data Engineer",
            "department": "Data & AI",
            "location": "Delhi, India",
            "bio": "Data pipeline specialist with strong SQL and Python skills.",
            "years_of_experience": 4.0,
            "open_to_remote": True,
            "open_to_gigs": True,
            "skills": [
                {"skill_id": "sk-python", "proficiency_level": 4, "years_of_experience": 4.0},
                {"skill_id": "sk-sql", "proficiency_level": 5, "years_of_experience": 4.0},
                {"skill_id": "sk-postgresql", "proficiency_level": 4, "years_of_experience": 3.0},
                {"skill_id": "sk-redis", "proficiency_level": 3, "years_of_experience": 1.5},
                {"skill_id": "sk-docker", "proficiency_level": 2, "years_of_experience": 0.5},
            ],
        },
        {
            "id": "emp-sneha",
            "first_name": "Sneha",
            "last_name": "Patil",
            "job_title": "Frontend Developer",
            "department": "Engineering",
            "location": "Chennai, India",
            "bio": "React specialist with experience in building enterprise dashboards.",
            "years_of_experience": 2.5,
            "open_to_remote": True,
            "open_to_gigs": True,
            "skills": [
                {"skill_id": "sk-react", "proficiency_level": 5, "years_of_experience": 2.5},
                {"skill_id": "sk-typescript", "proficiency_level": 4, "years_of_experience": 2.0},
                {"skill_id": "sk-vue", "proficiency_level": 3, "years_of_experience": 1.0},
                {"skill_id": "sk-git", "proficiency_level": 4, "years_of_experience": 2.5},
            ],
        },
        {
            "id": "emp-arjun",
            "first_name": "Arjun",
            "last_name": "Singh",
            "job_title": "Backend Developer",
            "department": "Engineering",
            "location": "Hyderabad, India",
            "bio": "Backend developer with GraphQL and Node.js focus. Learning Python.",
            "years_of_experience": 2.0,
            "open_to_remote": True,
            "open_to_gigs": True,
            "skills": [
                {"skill_id": "sk-graphql", "proficiency_level": 4, "years_of_experience": 2.0},
                {"skill_id": "sk-python", "proficiency_level": 2, "years_of_experience": 0.5},
                {"skill_id": "sk-postgresql", "proficiency_level": 2, "years_of_experience": 1.0},
                {"skill_id": "sk-restapi", "proficiency_level": 3, "years_of_experience": 1.5},
                {"skill_id": "sk-git", "proficiency_level": 4, "years_of_experience": 2.0},
            ],
        },
        {
            "id": "emp-meena",
            "first_name": "Meena",
            "last_name": "Raj",
            "job_title": "AI Research Engineer",
            "department": "Data & AI",
            "location": "Bangalore, India",
            "bio": "AI researcher with specialization in NLP and transformer models.",
            "years_of_experience": 5.0,
            "open_to_remote": True,
            "open_to_gigs": True,
            "skills": [
                {"skill_id": "sk-python", "proficiency_level": 5, "years_of_experience": 5.0},
                {"skill_id": "sk-ml", "proficiency_level": 5, "years_of_experience": 4.0},
                {"skill_id": "sk-nlp", "proficiency_level": 5, "years_of_experience": 3.5},
                {"skill_id": "sk-pytorch", "proficiency_level": 5, "years_of_experience": 3.0},
                {"skill_id": "sk-fastapi", "proficiency_level": 2, "years_of_experience": 0.5},
                {"skill_id": "sk-docker", "proficiency_level": 3, "years_of_experience": 2.0},
            ],
        },
        {
            "id": "emp-suresh",
            "first_name": "Suresh",
            "last_name": "Babu",
            "job_title": "Cloud Architect",
            "department": "Operations",
            "location": "Chennai, India",
            "bio": "Cloud infrastructure specialist with strong AWS and Kubernetes expertise.",
            "years_of_experience": 7.0,
            "open_to_remote": True,
            "open_to_gigs": False,
            "skills": [
                {"skill_id": "sk-aws", "proficiency_level": 5, "years_of_experience": 6.0},
                {"skill_id": "sk-kubernetes", "proficiency_level": 5, "years_of_experience": 4.0},
                {"skill_id": "sk-docker", "proficiency_level": 5, "years_of_experience": 5.0},
                {"skill_id": "sk-python", "proficiency_level": 3, "years_of_experience": 3.0},
                {"skill_id": "sk-git", "proficiency_level": 5, "years_of_experience": 7.0},
            ],
        },
        {
            "id": "emp-lakshmi",
            "first_name": "Lakshmi",
            "last_name": "Venkat",
            "job_title": "Product Manager",
            "department": "Product",
            "location": "Mumbai, India",
            "bio": "Product manager with technical background in backend systems.",
            "years_of_experience": 6.0,
            "open_to_remote": True,
            "open_to_gigs": False,
            "skills": [
                {"skill_id": "sk-agile", "proficiency_level": 5, "years_of_experience": 6.0},
                {"skill_id": "sk-python", "proficiency_level": 2, "years_of_experience": 1.0},
                {"skill_id": "sk-sql", "proficiency_level": 3, "years_of_experience": 3.0},
            ],
        },
        {
            "id": "emp-nitin",
            "first_name": "Nitin",
            "last_name": "Gupta",
            "job_title": "Senior Full Stack Engineer",
            "department": "Engineering",
            "location": "Pune, India",
            "bio": "Full-stack engineer with strong React and Python backend experience.",
            "years_of_experience": 5.0,
            "open_to_remote": True,
            "open_to_gigs": True,
            "skills": [
                {"skill_id": "sk-python", "proficiency_level": 4, "years_of_experience": 4.0},
                {"skill_id": "sk-fastapi", "proficiency_level": 3, "years_of_experience": 1.5},
                {"skill_id": "sk-react", "proficiency_level": 5, "years_of_experience": 4.0},
                {"skill_id": "sk-typescript", "proficiency_level": 4, "years_of_experience": 3.0},
                {"skill_id": "sk-postgresql", "proficiency_level": 3, "years_of_experience": 2.0},
                {"skill_id": "sk-docker", "proficiency_level": 3, "years_of_experience": 2.0},
                {"skill_id": "sk-git", "proficiency_level": 5, "years_of_experience": 5.0},
            ],
        },
        {
            "id": "emp-pooja",
            "first_name": "Pooja",
            "last_name": "Krishnaswamy",
            "job_title": "Data Scientist",
            "department": "Data & AI",
            "location": "Bangalore, India",
            "bio": "Data scientist with strong Python and ML skills, transitioning to MLOps.",
            "years_of_experience": 3.0,
            "open_to_remote": True,
            "open_to_gigs": True,
            "skills": [
                {"skill_id": "sk-python", "proficiency_level": 5, "years_of_experience": 3.0},
                {"skill_id": "sk-ml", "proficiency_level": 4, "years_of_experience": 2.5},
                {"skill_id": "sk-sql", "proficiency_level": 4, "years_of_experience": 2.5},
                {"skill_id": "sk-pytorch", "proficiency_level": 3, "years_of_experience": 1.5},
                {"skill_id": "sk-fastapi", "proficiency_level": 2, "years_of_experience": 0.5},
                {"skill_id": "sk-docker", "proficiency_level": 2, "years_of_experience": 0.5},
            ],
        },
        {
            "id": "emp-vijay",
            "first_name": "Vijay",
            "last_name": "Anand",
            "job_title": "DevOps Engineer",
            "department": "Operations",
            "location": "Chennai, India",
            "bio": "CI/CD specialist with strong Docker and Kubernetes expertise.",
            "years_of_experience": 3.5,
            "open_to_remote": True,
            "open_to_gigs": True,
            "skills": [
                {"skill_id": "sk-docker", "proficiency_level": 5, "years_of_experience": 3.5},
                {"skill_id": "sk-kubernetes", "proficiency_level": 4, "years_of_experience": 2.0},
                {"skill_id": "sk-aws", "proficiency_level": 3, "years_of_experience": 2.0},
                {"skill_id": "sk-python", "proficiency_level": 3, "years_of_experience": 2.0},
                {"skill_id": "sk-git", "proficiency_level": 5, "years_of_experience": 3.5},
            ],
        },
        {
            "id": "emp-ashwin",
            "first_name": "Ashwin",
            "last_name": "Prabhu",
            "job_title": "Backend Developer",
            "department": "Engineering",
            "location": "Coimbatore, India",
            "bio": "Python backend developer specializing in Django REST framework.",
            "years_of_experience": 2.0,
            "open_to_remote": True,
            "open_to_gigs": True,
            "skills": [
                {"skill_id": "sk-python", "proficiency_level": 3, "years_of_experience": 2.0},
                {"skill_id": "sk-django", "proficiency_level": 4, "years_of_experience": 2.0},
                {"skill_id": "sk-postgresql", "proficiency_level": 3, "years_of_experience": 1.5},
                {"skill_id": "sk-restapi", "proficiency_level": 3, "years_of_experience": 2.0},
                {"skill_id": "sk-git", "proficiency_level": 3, "years_of_experience": 2.0},
            ],
        },
        {
            "id": "emp-deepa",
            "first_name": "Deepa",
            "last_name": "Mohan",
            "job_title": "UI/UX Designer & Frontend Dev",
            "department": "Product",
            "location": "Bangalore, India",
            "bio": "Design-focused frontend developer with React and Vue expertise.",
            "years_of_experience": 3.0,
            "open_to_remote": True,
            "open_to_gigs": True,
            "skills": [
                {"skill_id": "sk-react", "proficiency_level": 4, "years_of_experience": 2.5},
                {"skill_id": "sk-vue", "proficiency_level": 4, "years_of_experience": 2.0},
                {"skill_id": "sk-typescript", "proficiency_level": 3, "years_of_experience": 1.5},
                {"skill_id": "sk-git", "proficiency_level": 3, "years_of_experience": 3.0},
            ],
        },
        {
            "id": "emp-muthukumar",
            "first_name": "Muthukumar",
            "last_name": "Selvam",
            "job_title": "Database Administrator",
            "department": "Operations",
            "location": "Chennai, India",
            "bio": "Database specialist with extensive PostgreSQL and MySQL experience.",
            "years_of_experience": 6.0,
            "open_to_remote": False,
            "open_to_gigs": True,
            "skills": [
                {"skill_id": "sk-postgresql", "proficiency_level": 5, "years_of_experience": 6.0},
                {"skill_id": "sk-sql", "proficiency_level": 5, "years_of_experience": 6.0},
                {"skill_id": "sk-redis", "proficiency_level": 3, "years_of_experience": 2.0},
                {"skill_id": "sk-python", "proficiency_level": 2, "years_of_experience": 1.0},
            ],
        },
        {
            "id": "emp-kavya",
            "first_name": "Kavya",
            "last_name": "Reddy",
            "job_title": "Software Engineer",
            "department": "Engineering",
            "location": "Hyderabad, India",
            "bio": "Software engineer building microservices with Celery and FastAPI.",
            "years_of_experience": 2.5,
            "open_to_remote": True,
            "open_to_gigs": True,
            "skills": [
                {"skill_id": "sk-python", "proficiency_level": 3, "years_of_experience": 2.5},
                {"skill_id": "sk-fastapi", "proficiency_level": 3, "years_of_experience": 1.5},
                {"skill_id": "sk-celery", "proficiency_level": 3, "years_of_experience": 1.0},
                {"skill_id": "sk-redis", "proficiency_level": 3, "years_of_experience": 1.0},
                {"skill_id": "sk-postgresql", "proficiency_level": 2, "years_of_experience": 1.0},
                {"skill_id": "sk-restapi", "proficiency_level": 3, "years_of_experience": 2.0},
                {"skill_id": "sk-git", "proficiency_level": 3, "years_of_experience": 2.5},
            ],
        },
    ]

    # ── HR Projects ──────────────────────────────────────────────────────────
    projects = [
        {
            "id": "proj-ai-platform",
            "name": "Eagle AI Platform v2",
            "department": "Engineering",
            "description": "Building the next generation AI-powered talent platform",
            "business_objective": "Improve talent matching accuracy by 40%",
            "duration_months": 8,
            "location": "Chennai / Remote",
            "work_mode": "hybrid",
            "headcount": 3,
            "priority": "critical",
            "status": "active",
        },
        {
            "id": "proj-data-pipeline",
            "name": "Real-Time Analytics Pipeline",
            "department": "Data & AI",
            "description": "Building scalable data pipeline for workforce analytics",
            "business_objective": "Enable real-time skill gap reporting",
            "duration_months": 4,
            "location": "Remote",
            "work_mode": "remote",
            "headcount": 2,
            "priority": "high",
            "status": "active",
        },
        {
            "id": "proj-mobile-app",
            "name": "Employee Mobile Application",
            "department": "Engineering",
            "description": "React Native mobile app for employee career development",
            "business_objective": "Increase employee engagement by 25%",
            "duration_months": 6,
            "location": "Bangalore",
            "work_mode": "hybrid",
            "headcount": 2,
            "priority": "medium",
            "status": "draft",
        },
        {
            "id": "proj-ml-hiring",
            "name": "ML-Assisted Hiring Platform",
            "department": "Data & AI",
            "description": "AI model to predict candidate success for technical roles",
            "business_objective": "Reduce time-to-hire by 30%",
            "duration_months": 5,
            "location": "Bangalore",
            "work_mode": "hybrid",
            "headcount": 2,
            "priority": "high",
            "status": "draft",
        },
        {
            "id": "proj-k8s-infra",
            "name": "Kubernetes Infrastructure Migration",
            "department": "Operations",
            "description": "Migrate all services from VMs to Kubernetes clusters",
            "business_objective": "Reduce infrastructure cost by 35%",
            "duration_months": 3,
            "location": "Remote",
            "work_mode": "remote",
            "headcount": 2,
            "priority": "high",
            "status": "active",
        },
    ]

    # ── Learning Resources ────────────────────────────────────────────────────
    learning_resources = [
        {
            "id": "lr-docker",
            "title": "Docker & Kubernetes: The Practical Guide",
            "description": "Learn Docker from scratch and Kubernetes for container orchestration",
            "provider": "Udemy",
            "url": "https://www.udemy.com/course/docker-kubernetes-the-practical-guide/",
            "skill_name": "Docker",
            "skill_level": "beginner",
            "duration_hours": 23,
            "resource_type": "course",
            "is_free": False,
        },
        {
            "id": "lr-fastapi",
            "title": "FastAPI Official Documentation & Tutorial",
            "description": "Complete guide to building production APIs with FastAPI",
            "provider": "FastAPI Docs",
            "url": "https://fastapi.tiangolo.com/tutorial/",
            "skill_name": "FastAPI",
            "skill_level": "beginner",
            "duration_hours": 8,
            "resource_type": "course",
            "is_free": True,
        },
        {
            "id": "lr-ml-coursera",
            "title": "Machine Learning Specialization",
            "description": "Andrew Ng's comprehensive ML course",
            "provider": "Coursera (DeepLearning.AI)",
            "url": "https://www.coursera.org/specializations/machine-learning-introduction",
            "skill_name": "Machine Learning",
            "skill_level": "beginner",
            "duration_hours": 40,
            "resource_type": "course",
            "is_free": False,
        },
        {
            "id": "lr-postgresql",
            "title": "The Complete SQL Bootcamp: Go from Zero to Hero in SQL",
            "description": "Master PostgreSQL from fundamentals to advanced queries",
            "provider": "Udemy",
            "url": "https://www.udemy.com/course/the-complete-sql-bootcamp/",
            "skill_name": "PostgreSQL",
            "skill_level": "beginner",
            "duration_hours": 9,
            "resource_type": "course",
            "is_free": False,
        },
        {
            "id": "lr-pytorch",
            "title": "PyTorch for Deep Learning & Machine Learning",
            "description": "Complete guide to building neural networks with PyTorch",
            "provider": "freeCodeCamp (YouTube)",
            "url": "https://www.youtube.com/watch?v=V_xro1bcAuA",
            "skill_name": "PyTorch",
            "skill_level": "intermediate",
            "duration_hours": 25,
            "resource_type": "video",
            "is_free": True,
        },
        {
            "id": "lr-kubernetes",
            "title": "Kubernetes for Developers",
            "description": "Practical Kubernetes for application developers",
            "provider": "Pluralsight",
            "url": "https://www.pluralsight.com/courses/kubernetes-developers",
            "skill_name": "Kubernetes",
            "skill_level": "intermediate",
            "duration_hours": 16,
            "resource_type": "course",
            "is_free": False,
        },
        {
            "id": "lr-aws",
            "title": "AWS Certified Solutions Architect – Associate",
            "description": "Comprehensive AWS architecture training and certification prep",
            "provider": "AWS Training",
            "url": "https://aws.amazon.com/training/",
            "skill_name": "AWS",
            "skill_level": "intermediate",
            "duration_hours": 30,
            "resource_type": "course",
            "is_free": False,
        },
        {
            "id": "lr-nlp",
            "title": "Natural Language Processing Specialization",
            "description": "4-course NLP specialization covering transformers and BERT",
            "provider": "Coursera (DeepLearning.AI)",
            "url": "https://www.coursera.org/specializations/natural-language-processing",
            "skill_name": "NLP",
            "skill_level": "advanced",
            "duration_hours": 36,
            "resource_type": "course",
            "is_free": False,
        },
        {
            "id": "lr-react",
            "title": "React - The Complete Guide (incl. React Router & Redux)",
            "description": "Modern React with hooks, routing, and state management",
            "provider": "Udemy",
            "url": "https://www.udemy.com/course/react-the-complete-guide-incl-redux/",
            "skill_name": "React",
            "skill_level": "beginner",
            "duration_hours": 48,
            "resource_type": "course",
            "is_free": False,
        },
        {
            "id": "lr-typescript",
            "title": "Understanding TypeScript",
            "description": "TypeScript from beginner to advanced with real projects",
            "provider": "Udemy",
            "url": "https://www.udemy.com/course/understanding-typescript/",
            "skill_name": "TypeScript",
            "skill_level": "beginner",
            "duration_hours": 15,
            "resource_type": "course",
            "is_free": False,
        },
        {
            "id": "lr-redis",
            "title": "Redis: The Complete Developer's Guide",
            "description": "Redis data structures, caching, pub/sub, and session management",
            "provider": "Udemy",
            "url": "https://www.udemy.com/course/redis-the-complete-developers-guide-p/",
            "skill_name": "Redis",
            "skill_level": "intermediate",
            "duration_hours": 18,
            "resource_type": "course",
            "is_free": False,
        },
        {
            "id": "lr-graphql",
            "title": "GraphQL with Python",
            "description": "Build GraphQL APIs with Strawberry and FastAPI",
            "provider": "YouTube / Official Docs",
            "url": "https://strawberry.rocks/docs/",
            "skill_name": "GraphQL",
            "skill_level": "intermediate",
            "duration_hours": 6,
            "resource_type": "course",
            "is_free": True,
        },
    ]

    return {
        "departments": departments,
        "skill_categories": skill_categories,
        "skills": skills,
        "users": users,
        "employees": employees,
        "projects": projects,
        "learning_resources": learning_resources,
    }
